---
- name: Minimal play
  hosts: localhost
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - ansible.builtin.command:
        # no name - may trigger task-name rule if we add it for shell
        cmd: echo hi
      changed_when: false
