---
# Handlers with issues
# L024: Handler without name

- ansible.builtin.service:
    name: httpd
    state: restarted

- name: Restart nginx
  ansible.builtin.service: # L026: Not FQCN
    name: nginx
    state: restarted
